### ISSUE TITLE
Using caseStmtMacros inside a generic function fails

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/fusion#103]
Using caseStmtMacros inside a generic function fails:

```nim
proc works() = 
  let a = some 2
  case a:
  of Some(@t):
    echo "some"
  of None():
    echo "none"

proc willFail[T]() = 
  let b = some 2
  case b:
  of Some(@t):
    echo "some"
  of None():
    echo "none"
```
Fails with: ``` Error: undeclared identifier: 'Some'``` in devel and 1.6.6

**Comment by Araq** [comment]
This is not a fusion bug but a Nim bug.

**Comment by jmgomez** [comment]
@Araq I see, thanks. Should I added it to Nim's issues or is already being tracked? If so, could you point out where? I would like to take a closer look to it

**Comment by Araq** [comment]
Add it as a Nim issue please.
