### ISSUE TITLE
fusion CI should run tests and docs for js

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/fusion#63]
refs https://github.com/nim-lang/fusion/pull/59#pullrequestreview-560240257

otherwise PR's like this https://github.com/nim-lang/fusion/pull/59 have tests that are never run.

Furthermore, we need to publish docs for js-only modules

/cc @juancarlospaco

**Comment by juancarlospaco** [comment]
We need someone to merge https://github.com/nim-lang/fusion/pull/54#issue-539041687 ?.
So it can advance further, or should it be mixed in between of that. :thinking:

**Comment by timotheecour** [comment]
ok! refs https://github.com/nim-lang/fusion/pull/54#issuecomment-753559215

**Comment by timotheecour** [comment]
Done, merged

**Comment by timotheecour** [comment]
also related but can be fixed independently: https://github.com/timotheecour/Nim/issues/197

**Comment by timotheecour** [comment]
closing since https://github.com/nim-lang/fusion/pull/64 mostly addressed this, will re-open a new issue to track the rest
