### ISSUE TITLE
deprecate or remove fusion/[jsformdata,jsheaders] because of the new [std/jsformdata,jsheaders]

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/fusion#74]
/cc @juancarlospaco 
* deprecate or remove fusion/[jsformdata,jsheaders] because of the new [std/jsformdata,jsheaders] (since https://github.com/nim-lang/Nim/pull/12531)

* what about fusion/js/jsxmlhttprequest.nim? is there equivalent in stdlib?

**Comment by juancarlospaco** [comment]
https://github.com/nim-lang/fusion/pull/75#issue-586188240

**Comment by juancarlospaco** [comment]
> is there equivalent in stdlib?

@timotheecour https://github.com/nim-lang/Nim/pull/16925#issuecomment-777228511

**Comment by timotheecour** [comment]
what do you mean? that comment you linked doesnt seem related to jsxmlhttprequest

**Comment by juancarlospaco** [comment]
@timotheecour People should be offered Fusion on install fulfilling the purpose of a stdlib extension driven by community.

**Comment by timotheecour** [comment]
my point was: if there's not stdlib module that makes fusion/js/jsxmlhttprequest.nim redundant, that we should keep fusion/js/jsxmlhttprequest.nim 
(unlike jsformdata,jsheaders which were made redundant by https://github.com/nim-lang/Nim/pull/12531)
